backend:
  name: git-gateway
  branch: main
media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/index.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/contact.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Privacy"
        name: "privacy"
        file: "src/privacy.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Terms"
        name: "terms"
        file: "src/terms.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "src/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Global"
        name: "site"
        file: "src/_data/site.json"
        fields:
          - { label: "Brand", name: "brand", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "WhatsApp URL", name: "whatsapp", widget: "string" }
          - { label: "Facebook", name: "facebook", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "TikTok", name: "tiktok", widget: "string" }
          - { label: "Stripe Link", name: "stripe_link", widget: "string" }
